on:
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: "1"

jobs:
  Quality:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      SKIP: no-commit-to-branch
    steps:
      - name: Install Python on the runner
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Checkout code so that it is available to use in the executing runner
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1
      - name: Check all files with pre-commit and update globally available pre-commit cache
        uses: pre-commit/action@v2.0.3
      - name: Check all commits
        uses: wagoid/commitlint-github-action@v5
