on:
  push:
    branches:
      - master

env:
  DOCKER_BUILDKIT: "1"

jobs:
  Quality:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
      - name: Install Python on the runner
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Checkout code so that it is available to use in the executing runner
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.45.0
      - name: Check all files with pre-commit and update globally available pre-commit cache
        uses: pre-commit/action@v2.0.3

  Release:
      needs: Quality
      timeout-minutes: 15
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code so that it is available to use in the executing runner
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Python Semantic Release
          uses: relekang/python-semantic-release@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
